spring:
  cache:
    infinispan:
      caches: IP, NAME, SURNAME, REGON

limits:
  IP:
    ttl: 5000 # 5 sekund
    attempts: 10
  NAME:
    ttl: 10000
    attempts: 5
  SURNAME:
    ttl: 5000
    attempts: 10
  REGON:
    ttl: 500
    attempts: 10
